/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyecto2_ipc1;

import HANDLERS1.BMPtoJPEGImage;
import HANDLERS1.JPEGHandler;
import HANDLERS1.JPEGImageCopy;
import HANDLERS1.JPEGImageHandlerBN;
import HANDLERS1.JPEGImageHandlerColors;
import HANDLERS1.JPEGImageHandlerRotator;
import HANDLERS1.JPEGtoBMPImage;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author DELL
 */
public class EditorsFrame extends javax.swing.JFrame {

    /**
     * Creates new form j
     */
    public EditorsFrame() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Editor"); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viceversaRadioButton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        copiaRadioButton = new javax.swing.JRadioButton();
        coloresRadioButton = new javax.swing.JRadioButton();
        modificarRadioButton = new javax.swing.JRadioButton();
        bnRaddioButton = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        RutaImagenLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        viceversaRadioButton.setText("JPEG a BMP o viceversa");

        jButton1.setText("Ejecutar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        copiaRadioButton.setText("copiaJPEG");

        coloresRadioButton.setText("Rojo Verde Azul Sepia");

        modificarRadioButton.setText("Modificar la imagen");

        bnRaddioButton.setText("Blanco y negro");

        jButton2.setText("Subir Imagen");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Salir");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel1.setText("EDITAR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RutaImagenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(viceversaRadioButton)
                                    .addComponent(bnRaddioButton, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(copiaRadioButton, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(coloresRadioButton, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(modificarRadioButton, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jButton3)
                                    .addComponent(jButton1)
                                    .addComponent(jButton2)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addComponent(jLabel1)))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(RutaImagenLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(viceversaRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(copiaRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(coloresRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(modificarRadioButton)
                        .addGap(18, 18, 18)
                        .addComponent(bnRaddioButton))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(83, 83, 83)
                        .addComponent(jButton3)))
                .addGap(58, 58, 58))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        String rutaArchivo = RutaImagenLabel.getText();
        
        
        if(viceversaRadioButton.isSelected() == true){
            JPEGtoBMPImage handlerJPG = new JPEGtoBMPImage(rutaArchivo);
            BMPtoJPEGImage handlerBMP = new BMPtoJPEGImage(rutaArchivo);
            
            try{
                JPEGHandler.runHandler(handlerJPG);
                JPEGHandler.runHandler(handlerBMP);
            } catch(Exception ex){
                ex.printStackTrace(); 
            }
        } else {
            System.out.println("falso");
        }
        
        if(copiaRadioButton.isSelected() == true){
            JPEGImageCopy handlerCopy = new JPEGImageCopy(rutaArchivo);
            
            try{
                JPEGHandler.runHandler(handlerCopy);
            } catch(Exception ex){
                ex.printStackTrace(); 
            } 
        }   else {
            System.out.println("falso");
        }
        
        if(coloresRadioButton.isSelected() == true){
            JPEGImageHandlerColors handlerColors = new JPEGImageHandlerColors(rutaArchivo);
            
            try{
                JPEGHandler.runHandler(handlerColors);
            } catch(Exception ex){
                ex.printStackTrace(); 
            }
        }   else {
            System.out.println("falso");
        }
        
        if(modificarRadioButton.isSelected() == true){
            JPEGImageHandlerRotator handlerModificar = new JPEGImageHandlerRotator(rutaArchivo);
            
            try{
                JPEGHandler.runHandler(handlerModificar);
            } catch(Exception ex){
                ex.printStackTrace(); 
            }
        }   else {
            System.out.println("falso");
        }
        
        if(bnRaddioButton.isSelected() == true){
            JPEGImageHandlerBN handlerBN = new JPEGImageHandlerBN(rutaArchivo);
            
            try{
                JPEGHandler.runHandler(handlerBN);
            } catch(Exception ex){
                ex.printStackTrace(); 
            }
        }   else {
            System.out.println("falso");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
                JFileChooser selector = new JFileChooser();
        int resultado = selector.showOpenDialog(this);
        if (resultado == JFileChooser.APPROVE_OPTION) {
            File archivo = selector.getSelectedFile();
            
            String rutaArchivo = archivo.getPath();
            RutaImagenLabel.setText(rutaArchivo);
        } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        VentanaPrincipalFrame login = new VentanaPrincipalFrame();
        login.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditorsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditorsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditorsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditorsFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditorsFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel RutaImagenLabel;
    private javax.swing.JRadioButton bnRaddioButton;
    private javax.swing.JRadioButton coloresRadioButton;
    private javax.swing.JRadioButton copiaRadioButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton modificarRadioButton;
    private javax.swing.JRadioButton viceversaRadioButton;
    // End of variables declaration//GEN-END:variables
}
